export enum MKey {
  MOUSE_LEFT       = 0,

  /* The opposite on the web */
  // MOUSE_RIGHT      = 1,
  // MOUSE_MIDDLE     = 2,
  MOUSE_RIGHT      = 2,
  MOUSE_MIDDLE     = 1,

  MOUSE_BACK       = 3,
  MOUSE_FORWARD    = 4,
  MOUSE_WHEEL_UP   = 5,
  MOUSE_WHEEL_DOWN = 6,
}

export enum Key {
  KeyA = "KeyA",
  KeyB = "KeyB",
  KeyC = "KeyC",
  KeyD = "KeyD",
  KeyE = "KeyE",
  KeyF = "KeyF",
  KeyG = "KeyG",
  KeyH = "KeyH",
  KeyI = "KeyI",
  KeyJ = "KeyJ",
  KeyK = "KeyK",
  KeyL = "KeyL",
  KeyM = "KeyM",
  KeyN = "KeyN",
  KeyO = "KeyO",
  KeyP = "KeyP",
  KeyQ = "KeyQ",
  KeyR = "KeyR",
  KeyS = "KeyS",
  KeyT = "KeyT",
  KeyU = "KeyU",
  KeyV = "KeyV",
  KeyW = "KeyW",
  KeyY = "KeyY",
  KeyX = "KeyX",
  KeyZ = "KeyZ",

  Numpad0 = "Numpad0",
  Numpad1 = "Numpad1",
  Numpad2 = "Numpad2",
  Numpad3 = "Numpad3",
  Numpad4 = "Numpad4",
  Numpad5 = "Numpad5",
  Numpad6 = "Numpad6",
  Numpad7 = "Numpad7",
  Numpad8 = "Numpad8",
  Numpad9 = "Numpad9",

  NumpadAdd = "NumpadAdd",
  NumpadSubtract = "NumpadSubtract",
  NumpadMultiply = "NumpadMultiply",
  NumpadDivide = "NumpadDivide",
  NumpadEqual = "NumpadEqual",
  NumpadDecimal = "NumpadDecimal",
  NumLock = "NumLock",
  NumpadEnter = "NumpadEnter",
  NumpadComma = "NumpadComma",

  Digit0 = "Digit0",
  Digit1 = "Digit1",
  Digit2 = "Digit2",
  Digit3 = "Digit3",
  Digit4 = "Digit4",
  Digit5 = "Digit5",
  Digit6 = "Digit6",
  Digit7 = "Digit7",
  Digit8 = "Digit8",
  Digit9 = "Digit9",

  F1 = "F1",
  F2 = "F2",
  F3 = "F3",
  F4 = "F4",
  F5 = "F5",
  F6 = "F6",
  F7 = "F7",
  F8 = "F8",
  F9 = "F9",
  F10 = "F10",
  F11 = "F11",
  F12 = "F12",
  F13 = "F13",
  F14 = "F14",
  F15 = "F15",
  F16 = "F16",
  F17 = "F17",
  F18 = "F18",
  F19 = "F19",
  F20 = "F20",

  ArrowLeft = "ArrowLeft",
  ArrowRight = "ArrowRight",
  ArrowDown = "ArrowDown",
  ArrowUp = "ArrowUp",

  Equal = "Equal",
  Minus = "Minus",

  PageUp = "PageUp",
  PageDown = "PageDown",

  OSRight = "OSRight",
  OSLeft = "OSLeft",

  AltLeft = "AltLeft",
  AltRight = "AltRight",
  ShiftLeft = "ShiftLeft",
  ShiftRight = "ShiftRight",
  ControlLeft = "ControlLeft",
  ControlRight = "ControlRight",

  Escape = "Escape",
  Enter = "Enter",
  CapsLock = "CapsLock",

  Help = "Insert",
  Home = "Home",
  Delete = "Delete",
  End = "End",

  BracketRight = "BracketRight",
  BracketLeft = "BracketLeft",
  Quote = "Quote",
  Semicolon = "Semicolon",
  Backslash = "Backslash",
  Comma = "Comma",
  Slash = "Slash",
  Period = "Period",
  Tab = "Tab",
  Space = "Space",
  Backquote = "Backquote",
  Backspace = "Backspace",

  IntlBackslash = "IntlBackslash",
  IntlYen = "IntlYen",
  IntlRo = "IntlRo",
}